[package]
name = "ntro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
clap_complete = "4.3.2"
serde = "1.0.167"
serde_yaml = "0.9.22"

[dev-dependencies]
insta = "1.30.0"
